# Generated by Django 4.0.3 on 2023-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gadha'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('Walet', models.CharField(max_length=50)),
                ('t_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='GAdha',
        ),
    ]
