# Generated by Django 4.0.3 on 2023-02-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_data_delete_gadha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_data',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='t_link',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='Walet',
            new_name='wallet_address',
        ),
    ]
