# Generated by Django 4.0.3 on 2023-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_all_data_rename_t_link_user_data_twitter_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='name',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='twitter_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
