# Generated by Django 4.0.3 on 2023-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_user_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
