# Generated by Django 4.0.3 on 2023-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='wallet_address',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
